/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface MarketIndex {
  'value' : number,
  'name' : string,
  'dailyChangePercent' : number,
}
export interface PortfolioEntry {
  'stock' : Stock,
  'buyPrice' : number,
  'quantity' : bigint,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface Stock {
  'name' : string,
  'dailyChangePercent' : number,
  'price' : number,
  'symbol' : string,
}
export type Time = bigint;
export interface Transaction {
  'transactionType' : string,
  'stock' : Stock,
  'timestamp' : bigint,
  'quantity' : bigint,
  'price' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStock' : ActorMethod<[Stock], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyStock' : ActorMethod<[string, bigint], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllMarketIndices' : ActorMethod<[], Array<MarketIndex>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllStocks' : ActorMethod<[], Array<Stock>>,
  'getBalance' : ActorMethod<[Principal], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMarketIndex' : ActorMethod<[string], [] | [MarketIndex]>,
  'getPortfolio' : ActorMethod<[Principal], Array<PortfolioEntry>>,
  'getStock' : ActorMethod<[string], [] | [Stock]>,
  'getTotalTradeVolume' : ActorMethod<[], bigint>,
  'getTotalUserCount' : ActorMethod<[], bigint>,
  'getTransactionHistory' : ActorMethod<[Principal], Array<Transaction>>,
  'getUserBalance' : ActorMethod<[], number>,
  'getUserPortfolio' : ActorMethod<[], Array<PortfolioEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sellStock' : ActorMethod<[string, bigint], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];