/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Stock = IDL.Record({
  'name' : IDL.Text,
  'dailyChangePercent' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MarketIndex = IDL.Record({
  'value' : IDL.Float64,
  'name' : IDL.Text,
  'dailyChangePercent' : IDL.Float64,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const PortfolioEntry = IDL.Record({
  'stock' : Stock,
  'buyPrice' : IDL.Float64,
  'quantity' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'transactionType' : IDL.Text,
  'stock' : Stock,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStock' : IDL.Func([Stock], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllMarketIndices' : IDL.Func([], [IDL.Vec(MarketIndex)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllStocks' : IDL.Func([], [IDL.Vec(Stock)], ['query']),
  'getBalance' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMarketIndex' : IDL.Func([IDL.Text], [IDL.Opt(MarketIndex)], ['query']),
  'getPortfolio' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PortfolioEntry)],
      ['query'],
    ),
  'getStock' : IDL.Func([IDL.Text], [IDL.Opt(Stock)], ['query']),
  'getTotalTradeVolume' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTransactionHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserPortfolio' : IDL.Func([], [IDL.Vec(PortfolioEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sellStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Stock = IDL.Record({
    'name' : IDL.Text,
    'dailyChangePercent' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MarketIndex = IDL.Record({
    'value' : IDL.Float64,
    'name' : IDL.Text,
    'dailyChangePercent' : IDL.Float64,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const PortfolioEntry = IDL.Record({
    'stock' : Stock,
    'buyPrice' : IDL.Float64,
    'quantity' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'transactionType' : IDL.Text,
    'stock' : Stock,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStock' : IDL.Func([Stock], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllMarketIndices' : IDL.Func([], [IDL.Vec(MarketIndex)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllStocks' : IDL.Func([], [IDL.Vec(Stock)], ['query']),
    'getBalance' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMarketIndex' : IDL.Func([IDL.Text], [IDL.Opt(MarketIndex)], ['query']),
    'getPortfolio' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PortfolioEntry)],
        ['query'],
      ),
    'getStock' : IDL.Func([IDL.Text], [IDL.Opt(Stock)], ['query']),
    'getTotalTradeVolume' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTransactionHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserPortfolio' : IDL.Func([], [IDL.Vec(PortfolioEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sellStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };